# Generated by Django 3.0.3 on 2021-03-31 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakenews', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='verdict',
            field=models.CharField(default=9, max_length=1),
            preserve_default=False,
        ),
    ]
