# Generated by Django 3.0.3 on 2021-04-01 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fakenews', '0002_claim_verdict'),
    ]

    operations = [
        migrations.AddField(
            model_name='claim',
            name='vector',
            field=models.TextField(default=9),
            preserve_default=False,
        ),
    ]
